version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - devdojo_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
    - "./src/main/resources/prometeus.yaml:/etc/prometheus/prometeus.yaml"
    command:
    - "--config.file=/etc/prometheus/prometeus.yaml"
    ports:
    - "9090:9090"

volumes:
  devdojo_data: